### PR TITLE
HTML and CSS Files structure

### PR DESCRIPTION
**Pull request by BSGreaves**

### CODE REVIEW

**Comment by zoeames** [comment]
@BSGreaves nice quiz!  A few things:  1.  There seems to be a bug when i click a card type something and then click somewhere on the screen without clicking enter.  It locks everything up and i can't click on anything else.  2.  json files are not js files.  they shouldn't be in your js file. 3.  Promises are cool but now is not the appropriate time to use one.  Switch to a callback to show your callback mastery.

**Comment by BSGreaves** [comment]
@zoeames Sounds good.
Re #1 "There seems to be a bug when i click a card type something and then click somewhere on the screen without clicking enter. It locks everything up and i can't click on anything else."
That's intentional - I put in measures to prevent multiple selections. Happy to change it though. Can you provide guidance since we're beyond the instructions now? Off the top of my head, I can A. add a "Save" button next to the input to make it clear how they can "unlock" the DOM, B. rewrite the code so it auto-saves the first selected card if a second card is selected. Thoughts? 
Re: the promise, I'll replace it, sorry.
Thanks!

**Comment by zoeames** [comment]
@BSGreaves sorry just seeing your comment.  Have it auto-save if a second card is selected

**Comment by BSGreaves** [comment]
@zoeames Changes made, users can now swap between cards at will.

**Comment by zoeames** [comment]
👍

**Pull request merged**
